<template>
    <div class="companies">
        <div class="banner ikarospartners">
            <div class="container h-100 d-flex align-items-center justify-content-center flex-column">
                <a href="#" class="btn btn-success">Visit Web Site</a>
            </div>
        </div>
        <div class="content py-lg-20 py-10">
            <div class="container">
                <div class="row mx-lg-0">
                    <div class="col-lg-6 pl-lg-0 pr-lg-6">
                        <p>Ikaros&Partners Human Resources and Training Consultancy which generated by the idea of qualified solution partnership for the requirements in the labor market, meet the demands of your recruitment process within several sectors such as sales and marketing, retail, engineering and production, IT, Logistics and supply chain, human resources, finance and accounting with its exclusive methods and broad candidate pool. Ikaros&Partners improves professional experience by supporting training and reconstruction process with its Solution Partnerships. Ikaros&Partners also provides overseas services with management team and co-founders.</p>
                    </div>
                    <div class="col-lg-6 mt-lg-0 mt-6 px-lg-0">
                        <img src="../assets/img/ikarospartners1.jpg" alt="" class="w-100">
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<style lang="scss" scoped>
    .ikarospartners{
        background: url("../assets/img/ikarospartners-banner.jpg") no-repeat center center;
    }
</style>
<script>
    export default {
        name: 'App',
        metaInfo: {
            title: 'ABK HOLDING',
            titleTemplate: '%s | Ikaros&Partners',
            meta: [
            { name: 'description', content: 'Ikaros&Partners Human Resources and Training Consultancy which generated by the idea of qualified solution partnership for the requirements in the labor market.' },
            ]
        },
    }
</script>